language: node_js
node_js: '8'

cache:
  directories:
    - node_modules

install:
  - yarn install

script:
  - yarn lint
  - yarn test
  - if [[ "$TRAVIS_PULL_REQUEST" == "true" ]]; then yarn build; fi

after_script: yarn coveralls
